# Generated by Django 3.2.8 on 2021-10-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='platform',
            field=models.CharField(choices=[('INST', 'INSTGRAM'), ('FB', 'FACEBOOK')], default=None, max_length=8),
        ),
        migrations.AddField(
            model_name='lead',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
