# Generated by Django 3.2.8 on 2021-10-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20211026_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('AT STORE', 'AT STORE'), ('IN STOCK', 'IN STOCK'), ('SHIPPING', 'SHIPPING'), ('DELIVERED', 'DELIVERED'), ('REJECTED', 'REJECTED'), ('PROBLEM', 'PROBLEM')], default=None, max_length=9),
        ),
        migrations.AddField(
            model_name='lead',
            name='time_of_delivered',
            field=models.DateTimeField(default='10:10'),
        ),
        migrations.AddField(
            model_name='lead',
            name='type',
            field=models.CharField(choices=[('GF', 'GIFTS'), ('BKS', 'BOOKS'), ('CLTHS', 'CLOTHES')], default=None, max_length=8),
        ),
    ]
