# Generated by Django 3.2.8 on 2021-10-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20211026_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='time_of_delivered',
            field=models.DateTimeField(default='2021-10-26 10:12'),
        ),
    ]
