# Generated by Django 3.2.8 on 2021-10-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_time_of_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='time_of_delivered',
        ),
    ]
