# Generated by Django 3.2.8 on 2021-10-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_remove_lead_time_of_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='type',
            field=models.CharField(choices=[('GF', 'GIFTS'), ('BKS', 'BOOKS'), ('CLTHS', 'CLOTHES')], default=None, max_length=9),
        ),
    ]
