# Generated by Django 3.2.8 on 2021-10-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='price',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='type',
        ),
    ]
