# Generated by Django 3.2.8 on 2021-10-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20211026_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='platform',
            field=models.CharField(choices=[('INST', 'INSTGRAM'), ('FB', 'FACEBOOK')], default=None, max_length=8),
        ),
        migrations.AddField(
            model_name='lead',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('AT STORE', 'AT STORE'), ('IN STOCK', 'IN STOCK'), ('SHIPPING', 'SHIPPING'), ('DELIVERED', 'DELIVERED'), ('REJECTED', 'REJECTED'), ('PROBLEM', 'PROBLEM')], default=None, max_length=9),
        ),
        migrations.AddField(
            model_name='lead',
            name='type',
            field=models.CharField(choices=[('GF', 'GIFTS'), ('BKS', 'BOOKS'), ('CLTHS', 'CLOTHES')], default=None, max_length=8),
        ),
    ]
