# Generated by Django 3.2.8 on 2021-10-26 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20211026_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='type',
        ),
    ]
