# Generated by Django 3.2.9 on 2021-11-07 06:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('wallet', models.IntegerField()),
                ('gifts', models.IntegerField()),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='logo.png', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('price', models.IntegerField()),
                ('gifts', models.BooleanField(default=False)),
                ('location', models.TextField()),
                ('note', models.CharField(max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_delivered', models.DateTimeField(default=datetime.datetime(2021, 11, 7, 6, 43, 7, 440783, tzinfo=utc), null=True)),
                ('status', models.CharField(choices=[('At Store', 'At Store'), ('In Stock', 'In Stock'), ('Shipping', 'Shipping'), ('Deliverd', 'Deliverd'), ('Rejected', 'Rejected'), ('Problem', 'Problem')], max_length=20, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
            ],
        ),
    ]
