# Generated by Django 3.2.9 on 2021-11-07 06:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_delivered',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 6, 43, 31, 720930, tzinfo=utc), null=True),
        ),
    ]
