# Generated by Django 3.2.9 on 2021-11-09 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.admin'),
        ),
    ]
