# Generated by Django 3.2.9 on 2021-11-12 04:39

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211112_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wallet',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='IQD', editable=False, max_digits=14, null=True),
        ),
    ]
