# Generated by Django 3.2.9 on 2021-11-12 04:54

from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customer_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wallet',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='IQD', editable=False, max_digits=14, null=True, validators=[djmoney.models.validators.MinMoneyValidator(250)]),
        ),
    ]
