# Generated by Django 3.2.9 on 2021-11-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customer_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gifts',
            field=models.IntegerField(default=0, editable=False, null=True),
        ),
    ]
