# Generated by Django 3.2.9 on 2021-11-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Deliverd', 'Deliverd'), ('Out For Delivery', 'Out for delivery')], max_length=20, null=True),
        ),
    ]
