# Generated by Django 3.2.9 on 2021-11-12 07:23

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customer_gifts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gifts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wallet',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='IQD', editable=False, max_digits=14),
        ),
    ]
