# Generated by Django 3.2.9 on 2021-11-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20211112_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('At Store', 'At Store'), ('In Stock', 'In Stock'), ('Shipping', 'Shipping'), ('Deliverd', 'Deliverd'), ('Rejected', 'Rejected'), ('Problem', 'Problem')], default='At Store', max_length=20, null=True),
        ),
    ]
