# Generated by Django 3.2.9 on 2021-11-12 07:35

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gifts',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wallet',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='IQD', max_digits=14),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('Books', 'Books'), ('Clothes', 'Clothes'), ('Makeup', 'Makeup')], default='Books', max_length=20, null=True),
        ),
    ]
