# Generated by Django 3.2.9 on 2021-11-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_order_date_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_delivered',
        ),
    ]
