# Generated by Django 3.2.9 on 2021-11-13 09:05

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211112_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wallet',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='IQD', editable=False, max_digits=14),
        ),
    ]
