# Generated by Django 3.2.9 on 2021-11-13 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customer_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('FB', 'Facebook'), ('IN', 'Insrgram')], max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.client'),
        ),
    ]
