# Generated by Django 3.2.9 on 2021-11-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform',
            field=models.CharField(choices=[('FB', 'Facebook'), ('IN', 'Instgram')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('Books', 'Books'), ('Clothes', 'Clothes'), ('Makeup', 'Makeup')], max_length=20, null=True),
        ),
    ]
