# Generated by Django 3.2.9 on 2021-11-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211113_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gifts',
            field=models.IntegerField(default=0),
        ),
    ]
