# Generated by Django 3.2.9 on 2021-11-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211107_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wallet',
            field=models.IntegerField(null=True),
        ),
    ]
