# Generated by Django 3.2.9 on 2021-11-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customer_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gifts',
            field=models.IntegerField(null=True),
        ),
    ]
