# Generated by Django 3.2.9 on 2021-11-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20211114_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('At Store', 'At Store'), ('In Stock', 'In Stock'), ('Shipping', 'Shipping'), ('Deliverd', 'Deliverd'), ('Rejected', 'Rejected'), ('Problem', 'Problem'), ('D&P', 'Deliverd&paid')], default='At Store', max_length=20, null=True),
        ),
    ]
